$script = <<-SCRIPT
echo I am provisioning...
loadkeys de
cd .
mkdir provisioning
cd provisioning
touch worked.txt
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "offensive-security/kali-linux"
  # Run Ansible from the Vagrant VM
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
  config.vm.provision "shell", inline: $script
  config.vm.provision "shell", inline: "cat ~vagrant/.ssh/me.pub >> ~vagrant/.ssh/authorized_keys"
end