$script = <<-SCRIPT
echo I am provisioning...
loadkeys de
cd .
mkdir provisioning
cd provisioning
touch worked.txt
SCRIPT

# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello World this should happen on both machines"

  config.vm.define "scanner" do |scanner|
	scanner.vm.box = "ubuntu/trusty64"
	scanner.vm.provision "shell", inline: $script
	end
  config.vm.define "vulnerable" do |vulnerable|
	vulnerable.vm.box = "ubuntu/trusty64"
	vulnerable.vm.provision "shell", inline: $script
	end
end