# -*- mode: ruby -*-
# vi: set ft=ruby :
# encoding: UTF-8

Vagrant.configure("2") do |config|
# Check if this even happens
  config.vm.provision "shell", inline: "echo Start the Vagrant Process"
  # Configuration for the ssh process
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  
  config.vm.define "vulnerable" do |vulnerable|
	vulnerable.vm.box = "rapid7/metasploitable3-ub1404"
	vulnerable.vm.network "private_network", ip: "172.16.16.3"
	vulnerable.vm.synced_folder "sync/", "/home/vagrant", create: true
	# Main provisioning with shell, maybe also abstract so ansible and docker and so are possible.
	vulnerable.vm.provision "shell", path: "vulnerable_provisioning.sh"
	# Additional provisioning
	# <--HOOK--> Hook to replace

  end

  config.vm.define "scanner" do |scanner|
	scanner.vm.box = "ubuntu/trusty64"
	scanner.vm.network "private_network", ip: "172.16.16.2"
	scanner.vm.synced_folder "sync/", "/home/vagrant", create: true
	scanner.vm.provision "shell", path: "scanner_provisioning.sh"
  end
end
