# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.define "manager" do |manager|
	  manager.vm.box = "daniele2010/ubuntu-14.04_x64-nagios"
	  manager.vm.network "private_network", ip: "172.168.178.2"
  end

  config.vm.define "scanner" do |scanner|
	scanner.vm.box = "ubuntu/trusty64"
	scanner.vm.network "private_network", ip: "172.168.178.3"
  end
end
